apiVersion: v1
kind: Service
metadata:
  name: demoservice
spec:
  selector:
    name: demoPod
    owner: Krihsana_N
    version: "beta"
    module: WebDemo
  type: NodePort
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
     nodePort: 30080
